services:
  jupyternotebook:
    image: "acevpn/gpu-jupyter-pytorch-dotnet:latest"
    container_name: jupyternotebook
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./JupyterNotebook:/home/jovyan/work
      #- ./JupyterNotebook:/home/jupyter/work
    ports:
      - "8888:8888/tcp"
    restart: unless-stopped  
    ipc: host
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                #device_ids: ['0']
                capabilities: [gpu,compute,utility,video]
    networks:
      - docker_network_bridge

networks:
  docker_network_bridge:
    external: true    
